# Generated by Django 3.0.1 on 2019-12-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('imdbID', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=4)),
            ],
        ),
    ]
