# Generated by Django 3.0.1 on 2020-01-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_favmovie_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favmovie',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='favmovie',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='favmovie',
            old_name='Year',
            new_name='year',
        ),
    ]
